### ISSUE TITLE
[IPC Library: File Watcher (nsfw)] Error: dlopen failed: cannot locate symbol

### ISSUE THREAD

**Issue by yozman** [Axosoft/nsfw#117]
doesn't work with android on termux

```sh
$ uname -a
Linux localhost 4.14.83-perf+ #1 SMP PREEMPT Wed May 6 14:25:36 CST 2020 aarch64 Android
```

```sh
$ code-server
info  Using config file ~/.config/code-server/config.yaml
info  Using user-data-dir ~/.local/share/code-server
info  code-server 3.4.1 48f7c2724827e526eeaa6c2c151c520f48a61259
info  HTTP server listening on http://0.0.0.0:8090
info    - No authentication
info    - Not serving HTTPS
[IPC Library: File Watcher (nsfw)] Error: dlopen failed: cannot locate symbol "_ZN14InotifyServiceC1ENSt6__ndk110shared_ptrI10EventQueueEENS0_12basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEE" referenced by "/data/data/com.termux/files/home/.config/yarn/global/node_modules/code-server/lib/vscode/node_modules/vscode-nsfw/build/Release/nsfw.node"...
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1250:18)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
    at Object.<anonymous> (/data/data/com.termux/files/home/.config/yarn/global/node_modules/code-server/lib/vscode/node_modules/vscode-nsfw/lib/src/index.js:3:16)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
    at t.load (/data/data/com.termux/files/home/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/loader.js:16:119)
    at e.load (/data/data/com.termux/files/home/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/loader.js:13:586)
    at i (/data/data/com.termux/files/home/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/loader.js:29:259)
    at Object.errorback (/data/data/com.termux/files/home/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/loader.js:29:383)
    at e.triggerErrorback (/data/data/com.termux/files/home/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/loader.js:13:955)
    at /data/data/com.termux/files/home/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/loader.js:13:659
    at ReadFileContext.callback (/data/data/com.termux/files/home/.config/yarn/global/node_modules/code-server/lib/vscode/out/vs/loader.js:16:494)
    at FSReqCallback.readFileAfterOpen [as oncomplete] (fs.js:260:13)
```

**Comment by yozman** [comment]
@implausible 
could you please look into this, too?
because of there isn't issue tab for <https://github.com/microsoft/vscode-nsfw>
