### ISSUE TITLE
Uncaught Error: Module did not self-register.

### ISSUE THREAD

**Issue by dasmikko** [Axosoft/nsfw#25]
I'm trying to use nsfw my my NWJS project, but i keep getting this error:

Uncaught Error: Module did not self-register.
    at Object.Module._extensions..node (module.js:640:18)
    at Module.load (module.js:512:32)
    at tryModuleLoad (module.js:471:12)
    at Function.Module._load (module.js:463:3)
    at Module.require (module.js:522:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (node_modules\nsfw\lib\src\index.js:1:80)
    at Module._compile (module.js:595:32)
    at Object.Module._extensions..js (module.js:610:10)
    at Module.load (module.js:512:32)

**Comment by implausible** [comment]
We currently do not support NWJS.

**Comment by dasmikko** [comment]
Okay, that explains why it doesn't work there.

_Sent from my LGE Nexus 5X using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by dein0s** [comment]
Got the same exception not using NWJS (first electron project, testing things around):
![error_img](https://i.imgur.com/RafvuLT.png)

OS: Windows 10
node: 8.7
npm: 5.4.2

Not sure what else I need to provide.

```
$ npm list
test_stuff@1.0.0 F:\Projects\test_stuff
+-- electron@1.7.9
| +-- @types/node@7.0.46
| +-- electron-download@3.3.0
| | +-- debug@2.6.9
| | | `-- ms@2.0.0
| | +-- fs-extra@0.30.0
| | | +-- graceful-fs@4.1.11 deduped
| | | +-- jsonfile@2.4.0 deduped
| | | +-- klaw@1.3.1 deduped
| | | +-- path-is-absolute@1.0.1 deduped
| | | `-- rimraf@2.6.2 deduped
| | +-- home-path@1.0.5
| | +-- minimist@1.2.0
| | +-- nugget@2.0.1
| | | +-- debug@2.6.9 deduped
| | | +-- minimist@1.2.0 deduped
| | | +-- pretty-bytes@1.0.4
| | | | +-- get-stdin@4.0.1
| | | | `-- meow@3.7.0
| | | |   +-- camelcase-keys@2.1.0
| | | |   | +-- camelcase@2.1.1
| | | |   | `-- map-obj@1.0.1 deduped
| | | |   +-- decamelize@1.2.0
| | | |   +-- loud-rejection@1.6.0
| | | |   | +-- currently-unhandled@0.4.1
| | | |   | | `-- array-find-index@1.0.2
| | | |   | `-- signal-exit@3.0.2
| | | |   +-- map-obj@1.0.1
| | | |   +-- minimist@1.2.0 deduped
| | | |   +-- normalize-package-data@2.4.0
| | | |   | +-- hosted-git-info@2.5.0
| | | |   | +-- is-builtin-module@1.0.0
| | | |   | | `-- builtin-modules@1.1.1
| | | |   | +-- semver@5.4.1 deduped
| | | |   | `-- validate-npm-package-license@3.0.1
| | | |   |   +-- spdx-correct@1.0.2
| | | |   |   | `-- spdx-license-ids@1.2.2
| | | |   |   `-- spdx-expression-parse@1.0.4
| | | |   +-- object-assign@4.1.1
| | | |   +-- read-pkg-up@1.0.1
| | | |   | +-- find-up@1.1.2
| | | |   | | +-- path-exists@2.1.0 deduped
| | | |   | | `-- pinkie-promise@2.0.1 deduped
| | | |   | `-- read-pkg@1.1.0
| | | |   |   +-- load-json-file@1.1.0
| | | |   |   | +-- graceful-fs@4.1.11 deduped
| | | |   |   | +-- parse-json@2.2.0
| | | |   |   | | `-- error-ex@1.3.1
| | | |   |   | |   `-- is-arrayish@0.2.1
| | | |   |   | +-- pify@2.3.0
| | | |   |   | +-- pinkie-promise@2.0.1 deduped
| | | |   |   | `-- strip-bom@2.0.0
| | | |   |   |   `-- is-utf8@0.2.1
| | | |   |   +-- normalize-package-data@2.4.0 deduped
| | | |   |   `-- path-type@1.1.0
| | | |   |     +-- graceful-fs@4.1.11 deduped
| | | |   |     +-- pify@2.3.0 deduped
| | | |   |     `-- pinkie-promise@2.0.1 deduped
| | | |   +-- redent@1.0.0
| | | |   | +-- indent-string@2.1.0
| | | |   | | `-- repeating@2.0.1
| | | |   | |   `-- is-finite@1.0.2
| | | |   | |     `-- number-is-nan@1.0.1 deduped
| | | |   | `-- strip-indent@1.0.1
| | | |   |   `-- get-stdin@4.0.1 deduped
| | | |   `-- trim-newlines@1.0.0
| | | +-- progress-stream@1.2.0
| | | | +-- speedometer@0.1.4
| | | | `-- through2@0.2.3
| | | |   +-- readable-stream@1.1.14
| | | |   | +-- core-util-is@1.0.2 deduped
| | | |   | +-- inherits@2.0.3 deduped
| | | |   | +-- isarray@0.0.1
| | | |   | `-- string_decoder@0.10.31
| | | |   `-- xtend@2.1.2
| | | |     `-- object-keys@0.4.0
| | | +-- request@2.83.0
| | | | +-- aws-sign2@0.7.0
| | | | +-- aws4@1.6.0
| | | | +-- caseless@0.12.0
| | | | +-- combined-stream@1.0.5
| | | | | `-- delayed-stream@1.0.0
| | | | +-- extend@3.0.1
| | | | +-- forever-agent@0.6.1
| | | | +-- form-data@2.3.1
| | | | | +-- asynckit@0.4.0
| | | | | +-- combined-stream@1.0.5 deduped
| | | | | `-- mime-types@2.1.17 deduped
| | | | +-- har-validator@5.0.3
| | | | | +-- ajv@5.2.3
| | | | | | +-- co@4.6.0
| | | | | | +-- fast-deep-equal@1.0.0
| | | | | | +-- json-schema-traverse@0.3.1
| | | | | | `-- json-stable-stringify@1.0.1
| | | | | |   `-- jsonify@0.0.0
| | | | | `-- har-schema@2.0.0
| | | | +-- hawk@6.0.2
| | | | | +-- boom@4.3.1
| | | | | | `-- hoek@4.2.0 deduped
| | | | | +-- cryptiles@3.1.2
| | | | | | `-- boom@5.2.0
| | | | | |   `-- hoek@4.2.0 deduped
| | | | | +-- hoek@4.2.0
| | | | | `-- sntp@2.0.2
| | | | |   `-- hoek@4.2.0 deduped
| | | | +-- http-signature@1.2.0
| | | | | +-- assert-plus@1.0.0
| | | | | +-- jsprim@1.4.1
| | | | | | +-- assert-plus@1.0.0 deduped
| | | | | | +-- extsprintf@1.3.0
| | | | | | +-- json-schema@0.2.3
| | | | | | `-- verror@1.10.0
| | | | | |   +-- assert-plus@1.0.0 deduped
| | | | | |   +-- core-util-is@1.0.2 deduped
| | | | | |   `-- extsprintf@1.3.0 deduped
| | | | | `-- sshpk@1.13.1
| | | | |   +-- asn1@0.2.3
| | | | |   +-- assert-plus@1.0.0 deduped
| | | | |   +-- bcrypt-pbkdf@1.0.1
| | | | |   | `-- tweetnacl@0.14.5 deduped
| | | | |   +-- dashdash@1.14.1
| | | | |   | `-- assert-plus@1.0.0 deduped
| | | | |   +-- ecc-jsbn@0.1.1
| | | | |   | `-- jsbn@0.1.1 deduped
| | | | |   +-- getpass@0.1.7
| | | | |   | `-- assert-plus@1.0.0 deduped
| | | | |   +-- jsbn@0.1.1
| | | | |   `-- tweetnacl@0.14.5
| | | | +-- is-typedarray@1.0.0
| | | | +-- isstream@0.1.2
| | | | +-- json-stringify-safe@5.0.1
| | | | +-- mime-types@2.1.17
| | | | | `-- mime-db@1.30.0
| | | | +-- oauth-sign@0.8.2
| | | | +-- performance-now@2.1.0
| | | | +-- qs@6.5.1
| | | | +-- safe-buffer@5.1.1
| | | | +-- stringstream@0.0.5
| | | | +-- tough-cookie@2.3.3
| | | | | `-- punycode@1.4.1
| | | | +-- tunnel-agent@0.6.0
| | | | | `-- safe-buffer@5.1.1 deduped
| | | | `-- uuid@3.1.0
| | | +-- single-line-log@1.1.2
| | | | `-- string-width@1.0.2
| | | |   +-- code-point-at@1.1.0
| | | |   +-- is-fullwidth-code-point@1.0.0
| | | |   | `-- number-is-nan@1.0.1
| | | |   `-- strip-ansi@3.0.1
| | | |     `-- ansi-regex@2.1.1
| | | `-- throttleit@0.0.2
| | +-- path-exists@2.1.0
| | | `-- pinkie-promise@2.0.1
| | |   `-- pinkie@2.0.4
| | +-- rc@1.2.2
| | | +-- deep-extend@0.4.2
| | | +-- ini@1.3.4
| | | +-- minimist@1.2.0 deduped
| | | `-- strip-json-comments@2.0.1
| | +-- semver@5.4.1
| | `-- sumchecker@1.3.1
| |   +-- debug@2.6.9 deduped
| |   `-- es6-promise@4.1.1
| `-- extract-zip@1.6.5
|   +-- concat-stream@1.6.0
|   | +-- inherits@2.0.3
|   | +-- readable-stream@2.3.3
|   | | +-- core-util-is@1.0.2
|   | | +-- inherits@2.0.3 deduped
|   | | +-- isarray@1.0.0
|   | | +-- process-nextick-args@1.0.7
|   | | +-- safe-buffer@5.1.1 deduped
|   | | +-- string_decoder@1.0.3
|   | | | `-- safe-buffer@5.1.1 deduped
|   | | `-- util-deprecate@1.0.2
|   | `-- typedarray@0.0.6
|   +-- debug@2.2.0
|   | `-- ms@0.7.1
|   +-- mkdirp@0.5.0
|   | `-- minimist@0.0.8
|   `-- yauzl@2.4.1
|     `-- fd-slicer@1.0.1
|       `-- pend@1.2.0
`-- nsfw@1.0.16
  +-- fs-extra@0.26.7
  | +-- graceful-fs@4.1.11
  | +-- jsonfile@2.4.0
  | | `-- graceful-fs@4.1.11 deduped
  | +-- klaw@1.3.1
  | | `-- graceful-fs@4.1.11 deduped
  | +-- path-is-absolute@1.0.1
  | `-- rimraf@2.6.2
  |   `-- glob@7.1.2
  |     +-- fs.realpath@1.0.0
  |     +-- inflight@1.0.6
  |     | +-- once@1.4.0 deduped
  |     | `-- wrappy@1.0.2
  |     +-- inherits@2.0.3 deduped
  |     +-- minimatch@3.0.4
  |     | `-- brace-expansion@1.1.8
  |     |   +-- balanced-match@1.0.0
  |     |   `-- concat-map@0.0.1
  |     +-- once@1.4.0
  |     | `-- wrappy@1.0.2 deduped
  |     `-- path-is-absolute@1.0.1 deduped
  +-- lodash.isinteger@4.0.4
  +-- lodash.isundefined@3.0.1
  +-- nan@2.7.0
  `-- promisify-node@0.3.0
    `-- nodegit-promise@4.0.0
      `-- asap@2.0.6
```

**Comment by dein0s** [comment]
Just made a quick test with electron tutorial, same exception. Any ideas/suggestions?
Was thinking to switch from chokidar because of https://github.com/paulmillr/chokidar/issues/643, but it seems that I'm stuck now :(

Steps are:
1) Clone tutorial and install packages
```
$ git clone https://github.com/electron/electron-quick-start.git
$ cd electron-quick-start
$ npm install
```
2) Install nsfw
```
$ npm install --save nsfw

> nsfw@1.0.16 install F:\Projects\hots_stats\electron-quick-start\node_modules\nsfw
> node-gyp rebuild


F:\Projects\hots_stats\electron-quick-start\node_modules\nsfw>if not defined npm_config_node_gyp (node "F:\Projects\nvm\v8.7.0\node_modu
les\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Warning: Missing input files:
F:\Projects\hots_stats\electron-quick-start\node_modules\nsfw\build\openpa\..\..\openpa\src\primitives\opa_nt_intrinics.h
Сборка проектов в этом решении по одному. Чтобы включить параллельную сборку, добавьте параметр "/m".
  opa_primitives.c
  opa_queue.c
  win_delay_load_hook.cc
  openpa.vcxproj -> F:\Projects\hots_stats\electron-quick-start\node_modules\nsfw\build\Release\\openpa.lib
  NSFW.cpp
  Queue.cpp
  NativeInterface.cpp
  ReadLoop.cpp
  ReadLoopRunner.cpp
F:\Projects\hots_stats\electron-quick-start\node_modules\nsfw\openpa\src\opa_queue.h(75): warning C4190: 'OPA_Shm_abs_to_rel' has C-lin
kage specified, but returns UDT 'OPA_Shm_rel_addr_t' which is incompatible with C (compiling source file ..\src\Queue.cpp) [F:\Projects
\hots_stats\electron-quick-start\node_modules\nsfw\build\nsfw.vcxproj]
  F:\Projects\hots_stats\electron-quick-start\node_modules\nsfw\openpa\src\opa_queue.h(59): note: see declaration of 'OPA_Shm_rel_addr_
  t' (compiling source file ..\src\Queue.cpp)
F:\Projects\hots_stats\electron-quick-start\node_modules\nsfw\openpa\src\opa_queue.h(84): warning C4190: 'OPA_Shm_swap_rel' has C-linka
ge specified, but returns UDT 'OPA_Shm_rel_addr_t' which is incompatible with C (compiling source file ..\src\Queue.cpp) [F:\Projects\h
ots_stats\electron-quick-start\node_modules\nsfw\build\nsfw.vcxproj]
  F:\Projects\hots_stats\electron-quick-start\node_modules\nsfw\openpa\src\opa_queue.h(59): note: see declaration of 'OPA_Shm_rel_addr_
  t' (compiling source file ..\src\Queue.cpp)
F:\Projects\hots_stats\electron-quick-start\node_modules\nsfw\openpa\src\opa_queue.h(94): warning C4190: 'OPA_Shm_cas_rel_null' has C-l
inkage specified, but returns UDT 'OPA_Shm_rel_addr_t' which is incompatible with C (compiling source file ..\src\Queue.cpp) [F:\Projec
ts\hots_stats\electron-quick-start\node_modules\nsfw\build\nsfw.vcxproj]
  F:\Projects\hots_stats\electron-quick-start\node_modules\nsfw\openpa\src\opa_queue.h(59): note: see declaration of 'OPA_Shm_rel_addr_
  t' (compiling source file ..\src\Queue.cpp)
F:\Projects\hots_stats\electron-quick-start\node_modules\nsfw\openpa\src\opa_queue.h(75): warning C4190: 'OPA_Shm_abs_to_rel' has C-lin
kage specified, but returns UDT 'OPA_Shm_rel_addr_t' which is incompatible with C (compiling source file ..\src\NSFW.cpp) [F:\Projects\
hots_stats\electron-quick-start\node_modules\nsfw\build\nsfw.vcxproj]
  F:\Projects\hots_stats\electron-quick-start\node_modules\nsfw\openpa\src\opa_queue.h(59): note: see declaration of 'OPA_Shm_rel_addr_
  t' (compiling source file ..\src\NSFW.cpp)
F:\Projects\hots_stats\electron-quick-start\node_modules\nsfw\openpa\src\opa_queue.h(84): warning C4190: 'OPA_Shm_swap_rel' has C-linka
ge specified, but returns UDT 'OPA_Shm_rel_addr_t' which is incompatible with C (compiling source file ..\src\NSFW.cpp) [F:\Projects\ho
ts_stats\electron-quick-start\node_modules\nsfw\build\nsfw.vcxproj]
  F:\Projects\hots_stats\electron-quick-start\node_modules\nsfw\openpa\src\opa_queue.h(59): note: see declaration of 'OPA_Shm_rel_addr_
  t' (compiling source file ..\src\NSFW.cpp)
F:\Projects\hots_stats\electron-quick-start\node_modules\nsfw\openpa\src\opa_queue.h(94): warning C4190: 'OPA_Shm_cas_rel_null' has C-l
inkage specified, but returns UDT 'OPA_Shm_rel_addr_t' which is incompatible with C (compiling source file ..\src\NSFW.cpp) [F:\Project
s\hots_stats\electron-quick-start\node_modules\nsfw\build\nsfw.vcxproj]
  F:\Projects\hots_stats\electron-quick-start\node_modules\nsfw\openpa\src\opa_queue.h(59): note: see declaration of 'OPA_Shm_rel_addr_
  t' (compiling source file ..\src\NSFW.cpp)
F:\Projects\hots_stats\electron-quick-start\node_modules\nsfw\openpa\src\opa_queue.h(75): warning C4190: 'OPA_Shm_abs_to_rel' has C-lin
kage specified, but returns UDT 'OPA_Shm_rel_addr_t' which is incompatible with C (compiling source file ..\src\NativeInterface.cpp) [F
:\Projects\hots_stats\electron-quick-start\node_modules\nsfw\build\nsfw.vcxproj]
  F:\Projects\hots_stats\electron-quick-start\node_modules\nsfw\openpa\src\opa_queue.h(59): note: see declaration of 'OPA_Shm_rel_addr_
  t' (compiling source file ..\src\NativeInterface.cpp)
F:\Projects\hots_stats\electron-quick-start\node_modules\nsfw\openpa\src\opa_queue.h(84): warning C4190: 'OPA_Shm_swap_rel' has C-linka
ge specified, but returns UDT 'OPA_Shm_rel_addr_t' which is incompatible with C (compiling source file ..\src\NativeInterface.cpp) [F:\
Projects\hots_stats\electron-quick-start\node_modules\nsfw\build\nsfw.vcxproj]
  F:\Projects\hots_stats\electron-quick-start\node_modules\nsfw\openpa\src\opa_queue.h(59): note: see declaration of 'OPA_Shm_rel_addr_
  t' (compiling source file ..\src\NativeInterface.cpp)
F:\Projects\hots_stats\electron-quick-start\node_modules\nsfw\openpa\src\opa_queue.h(94): warning C4190: 'OPA_Shm_cas_rel_null' has C-l
inkage specified, but returns UDT 'OPA_Shm_rel_addr_t' which is incompatible with C (compiling source file ..\src\NativeInterface.cpp) 
[F:\Projects\hots_stats\electron-quick-start\node_modules\nsfw\build\nsfw.vcxproj]
  F:\Projects\hots_stats\electron-quick-start\node_modules\nsfw\openpa\src\opa_queue.h(59): note: see declaration of 'OPA_Shm_rel_addr_
  t' (compiling source file ..\src\NativeInterface.cpp)
F:\Projects\hots_stats\electron-quick-start\node_modules\nsfw\openpa\src\opa_queue.h(75): warning C4190: 'OPA_Shm_abs_to_rel' has C-lin
kage specified, but returns UDT 'OPA_Shm_rel_addr_t' which is incompatible with C (compiling source file ..\src\win32\ReadLoop.cpp) [F:
\Projects\hots_stats\electron-quick-start\node_modules\nsfw\build\nsfw.vcxproj]
  F:\Projects\hots_stats\electron-quick-start\node_modules\nsfw\openpa\src\opa_queue.h(59): note: see declaration of 'OPA_Shm_rel_addr_
  t' (compiling source file ..\src\win32\ReadLoop.cpp)
F:\Projects\hots_stats\electron-quick-start\node_modules\nsfw\openpa\src\opa_queue.h(84): warning C4190: 'OPA_Shm_swap_rel' has C-linka
ge specified, but returns UDT 'OPA_Shm_rel_addr_t' which is incompatible with C (compiling source file ..\src\win32\ReadLoop.cpp) [F:\P
rojects\hots_stats\electron-quick-start\node_modules\nsfw\build\nsfw.vcxproj]
  F:\Projects\hots_stats\electron-quick-start\node_modules\nsfw\openpa\src\opa_queue.h(59): note: see declaration of 'OPA_Shm_rel_addr_
  t' (compiling source file ..\src\win32\ReadLoop.cpp)
F:\Projects\hots_stats\electron-quick-start\node_modules\nsfw\openpa\src\opa_queue.h(75): warning C4190: 'OPA_Shm_abs_to_rel' has C-lin
kage specified, but returns UDT 'OPA_Shm_rel_addr_t' which is incompatible with C (compiling source file ..\src\win32\ReadLoopRunner.cp
p) [F:\Projects\hots_stats\electron-quick-start\node_modules\nsfw\build\nsfw.vcxproj]
F:\Projects\hots_stats\electron-quick-start\node_modules\nsfw\openpa\src\opa_queue.h(94): warning C4190: 'OPA_Shm_cas_rel_null' has C-l
inkage specified, but returns UDT 'OPA_Shm_rel_addr_t' which is incompatible with C (compiling source file ..\src\win32\ReadLoop.cpp) [
F:\Projects\hots_stats\electron-quick-start\node_modules\nsfw\build\nsfw.vcxproj]
  F:\Projects\hots_stats\electron-quick-start\node_modules\nsfw\openpa\src\opa_queue.h(59): note: see declaration of 'OPA_Shm_rel_addr_
  t' (compiling source file ..\src\win32\ReadLoopRunner.cpp)
  F:\Projects\hots_stats\electron-quick-start\node_modules\nsfw\openpa\src\opa_queue.h(59): note: see declaration of 'OPA_Shm_rel_addr_
  t' (compiling source file ..\src\win32\ReadLoop.cpp)
F:\Projects\hots_stats\electron-quick-start\node_modules\nsfw\openpa\src\opa_queue.h(84): warning C4190: 'OPA_Shm_swap_rel' has C-linka
ge specified, but returns UDT 'OPA_Shm_rel_addr_t' which is incompatible with C (compiling source file ..\src\win32\ReadLoopRunner.cpp)
 [F:\Projects\hots_stats\electron-quick-start\node_modules\nsfw\build\nsfw.vcxproj]
  F:\Projects\hots_stats\electron-quick-start\node_modules\nsfw\openpa\src\opa_queue.h(59): note: see declaration of 'OPA_Shm_rel_addr_
  t' (compiling source file ..\src\win32\ReadLoopRunner.cpp)
F:\Projects\hots_stats\electron-quick-start\node_modules\nsfw\openpa\src\opa_queue.h(94): warning C4190: 'OPA_Shm_cas_rel_null' has C-l
inkage specified, but returns UDT 'OPA_Shm_rel_addr_t' which is incompatible with C (compiling source file ..\src\win32\ReadLoopRunner.
cpp) [F:\Projects\hots_stats\electron-quick-start\node_modules\nsfw\build\nsfw.vcxproj]
  F:\Projects\hots_stats\electron-quick-start\node_modules\nsfw\openpa\src\opa_queue.h(59): note: see declaration of 'OPA_Shm_rel_addr_
  t' (compiling source file ..\src\win32\ReadLoopRunner.cpp)
..\src\NSFW.cpp(159): warning C4996: 'v8::Function::NewInstance': was declared deprecated [F:\Projects\hots_stats\electron-quick-start\
node_modules\nsfw\build\nsfw.vcxproj]
  c:\users\dein0s\.node-gyp\8.7.0\include\node\v8.h(3836): note: see declaration of 'v8::Function::NewInstance'
     Creating library F:\Projects\hots_stats\electron-quick-start\node_modules\nsfw\build\Release\nsfw.lib and object F:\Projects\hots_
  stats\electron-quick-start\node_modules\nsfw\build\Release\nsfw.exp
  Generating code
  Finished generating code
  nsfw.vcxproj -> F:\Projects\hots_stats\electron-quick-start\node_modules\nsfw\build\Release\\nsfw.node
  nsfw.vcxproj -> F:\Projects\hots_stats\electron-quick-start\node_modules\nsfw\build\Release\nsfw.pdb (Full PDB)
+ nsfw@1.0.16
added 8 packages in 8.134s
```
3) Modify *main.js*
```
const nsfw = require('nsfw')
```
4) Start app
```
$ npm start
```
![error_screen](https://i.imgur.com/UUAjwbi.png)
